server:
  port: 8083

spring:

  config:
    import: optional:file:.env[.properties]

  application:
    name: sawit-panen

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&channelBinding=require
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update

grpc:
  server:
    enabled: ${GRPC_SERVER_ENABLED:true}
    port: ${GRPC_PORT:9093}
